version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api-builder
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./apps/api:/app/apps/api
    command: npm run start

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web-builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./apps/web:/app/apps/web
    command: npm run preview

  # Development setup
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: npm run dev

